[package]
name = "token_contract"
authors = [""]
compiler_version = ">=0.18.0"
type = "contract"

[dependencies]
aztec = { git = 'https://github.com/AztecProtocol/aztec-packages/', tag = 'aztec-packages-v0.16.7', directory = 'yarn-project/aztec-nr/aztec' }
safe_math = { git = 'https://github.com/AztecProtocol/aztec-packages/', tag = 'aztec-packages-v0.16.7', directory = 'yarn-project/aztec-nr/safe-math' }
authwit = { git = 'https://github.com/AztecProtocol/aztec-packages/', tag = 'aztec-packages-v0.16.7', directory = 'yarn-project/aztec-nr/authwit' }
protocol_types = { git = 'https://github.com/AztecProtocol/aztec-packages/', tag = 'aztec-packages-v0.16.7', directory = 'yarn-project/noir-protocol-circuits/src/crates/types' }